Server:
  port: 8082

# 设置上传文件的临时存储路径
# 设置上传文件的临时存储路径
upload:
  directory: E:\temp\



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wesay?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.chat: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status # 全局逻辑删除字段名
      logic-delete-value: 0 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值
#  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml,classpath*:com/chat/wesay/mapper/*.xml
#
#mybatis:
#  #在,逗号前引入插件的配置,后面的是自己的
#  table:
#    auto: add
#    #create    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
#    #update    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
#    #none      系统不做任何处理。
#    #add       新增表/新增字段/新增索引/新增唯一约束的功能，不做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
#  model:
#    pack: com.chat.wesay.pojo  #扫描自己用于创建表的对象的包名，多个包用“,”隔开
#  database:
#    type: mysql #数据库类型 目前只支持mysql



